### ISSUE TITLE
Possible double-read

### ISSUE THREAD

**Issue by CthulhuDen** [leohaskell/skip-var#1]
First thread (readSVar) | Second thread (putSVar)
-------------------------------|----------------------------------
takeMVar lock | _
 _ | _ <- takeMVar var
 _ | hasToNotify <- isEmptyMVar lock -- True
 _ | putMVar var value -- var has new value
value <- takeMVar var -- new value read | _
putMVar var value | _
_ | when hasToNotify $ putMVar lock ()

In the end lock (notification flag) is set, although the new value is already read once, so it's going to be read again.

**Comment by dtaskoff** [comment]
Thank you, mate!
As much as I wanted to get rid of that third `MVar` (like written in the [paper](https://www.microsoft.com/en-us/research/wp-content/uploads/1996/01/concurrent-haskell.pdf)), seems like it's not possible to synchronise the changes to the `lock` without it :/
I'll push a fix today.

**Comment by dtaskoff** [comment]
You can check #2 if you're interested : )
